---
- fail: msg="JAVA_HOME is not set!"
  when: lookup('env','JAVA_HOME') == ''

- set_fact:
    jenkins_url: "http://{{ansible_ssh_host}}:{{jenkins_http_port}}"

- set_fact: container_ip={{ansible_host}}
- include: ansible-roles/includes/wait-until-jenkins-is-available.yml

- name: create staging dir for CLI
  local_action: file path={{local_cli_dir}} state=directory

- name: get Jenkins CLI Jar
  local_action: get_url url={{jenkins_url}}/jnlpJars/jenkins-cli.jar dest={{local_cli_dir}}

- set_fact: java_path="{{lookup('env','JAVA_HOME')}}/bin/java"
- set_fact: cli_cmd="{{java_path}} -jar {{local_cli_dir}}/jenkins-cli.jar -s {{jenkins_url}}"

- name: get initial admin password
  shell: cat {{jenkins_home}}/secrets/initialAdminPassword
  become: true
  register: jenkins_initial_admin_pwd

- debug: var=initial_admin_pwd
- name: set cli credentials from initial admin password
  set_fact: cli_creds="--username admin --password {{jenkins_initial_admin_pwd.stdout}}"

- name: test cli
  local_action: shell {{cli_cmd}} help {{cli_creds}}
