---
- name: Create RG
  azure_rm_resourcegroup:
    name: "{{rg_name}}"
    location: "{{location}}"
    state: present

- name: Create VNET
  azure_rm_virtualnetwork:
    resource_group: "{{vm_vnet_rg_name}}"
    name: "{{vm_vnet_name}}"
    address_prefixes: "{{vm_vnet_addr_prefix}}"

- name: Add Subnets to VNET
  azure_rm_subnet:
    resource_group: "{{vm_vnet_rg_name}}"
    name: "{{vm_subnet_name}}"
    address_prefix: "{{vm_subnet_addr_prefix}}"
    virtual_network: "{{vm_vnet_name}}"
    state: present

- name: Create Pub IP
  azure_rm_publicipaddress:
    resource_group: "{{rg_name}}"
    name: "{{vm_pubip_name}}"
    allocation_method: '{{vm_ip_allocation}}'

- name: get your IP
  uri:
    url: http://ipinfo.io/ip
    return_content: yes
  register: ip_output

- set_fact: ansible_machine_ip={{ip_output.content | replace('\n','')}}

- debug:
    msg: "Your IP: {{ansible_machine_ip}}"

- azure_rm_securitygroup:
    resource_group: '{{rg_name}}'
    name: '{{vm_nsg_name}}'
    purge_rules: yes
    rules: '{{vm_nsg_rules}}'
- name: Create NIC with Public IP
  azure_rm_networkinterface:
    resource_group: "{{rg_name}}"
    name: "{{vm_nic_name}}"
    virtual_network: "{{vm_vnet_name}}"
    subnet: "{{vm_subnet_name}}"
    ip_configurations:
    - name: '{{vm_pubip_name}}'
      public_ip_address_name: "{{vm_pubip_name}}"
    security_group_name: '{{vm_nsg_name}}'

- azure_rm_virtualmachine:
    resource_group: "{{rg_name}}"
    name: "{{vm_name}}"
    vm_size: "{{vm_size}}"
    admin_username: "{{vm_username}}"
    admin_password: "{{vault_vm_password}}"
    os_type: "{{vm_os_type}}"
    network_interfaces: "{{vm_nic_name}}"
    subnet_name: "{{vm_subnet_name}}"
    virtual_network_resource_group: "{{vm_vnet_rg_name}}"
    virtual_network_name: "{{vm_vnet_name}}"
    image: "{{vm_image}}"
    tags: "{{vm_tags}}"
    managed_disk_type: Standard_LRS



