---
- name: get hosts IP address
  local_action: command wget http://ipinfo.io/ip -qO -
  register: my_ipaddr

- name: install prerequisites
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - python
  become: true

- name: install pip
  shell: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" && python get-pip.py
  become: true

- name: install boto
  pip:
    name: boto
    state: present
  become: true

