---
- name: List existing secrets named {{sm_secret_name}}.
  shell: aws secretsmanager list-secrets --query 'SecretList' --output text --region '{{ec2_region}}'
  register: sm_existing_secrets
  changed_when: false

- name: Create new secret string from Ansible variable.
  shell: |
    aws secretsmanager create-secret \
    --name {{sm_secret_name}} \
    --description 'Ansible-Managed Secret' \
    --secret-string '{{sm_secret_string}}' \
    --region '{{ec2_region}}'
  when: 'sm_secret_name not in sm_existing_secrets.stdout'
  no_log: true

# To retrieve the secret value, use:
# aws secretsmanager get-secret-value --secret-id {{sm_secret_name}} --query 'SecretString' --output text
