---
# Prerequisites on localhost (Ansible Controller) to run Ansible AWS modules

- block:
  - name: include role to install python pip.
    include_role:
      name: common 
      tasks_from: install-pip 
  - name: ensure prerequisite pip packages
    pip:
      name: '{{item}}'
      state: present
    with_items:
    - boto
    - boto3
  become: true

- name: Fail if Ansible < 2.5
  fail: msg="Ansible 2.5+ required"
  when: ansible_version.major <= 2 and ansible_version.minor < 5
