---

- include: 'packages.yml'

# docker needs to expose its API
# so we need to push our defaults file in
- name: push docker service settings
  template:
    src: sysconfig.docker
    dest: /etc/sysconfig/docker
  when: ansible_distribution == 'CentOS'

- name: push docker service settings
  template:
    src: default.docker
    dest: /etc/default/docker
  when: ansible_distribution == 'Ubuntu'

- name: create docker group
  group:
    name: docker

- name: add ec2 user to docker group
  # command: usermod -a -G docker ec2-user
  user:
    name: "{{ docker_user }}"
    groups: docker

- name: restart docker service
  service:
    name: docker
    state: restarted
