---

- include: 'packages.yml'

# docker needs to expose its API
# so we need to push our defaults file in
- name: push docker service settings
  template:
    src: sysconfig.docker
    dest: /etc/sysconfig/docker
  when: ansible_distribution == 'CentOS'
  become: true

- name: push docker service settings for trusty
  template:
    src: default.docker
    dest: /etc/default/docker
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  become: true

- name: push docker service settings for xenial
  block:
  - template:
      src: daemon.json
      dest: /etc/docker/daemon.json
      mode: 0755
  - file:
      name: /etc/systemd/system/docker.service.d
      state: directory
      owner: root
      mode: 0755
  - template:
      src: systemd.docker
      dest: /etc/systemd/system/docker.service.d/docker.conf
    notify: restart docker
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
  become: true


- name: create docker group
  group:
    name: docker
  become: true

- name: Create a Docker user and add that to docker group to be able to run docker containers without sudo.
  user:
    name: "{{ docker_user }}"
    groups: docker
  become: true

- name: start docker service
  service:
    name: docker
    state: started
  become: true
