---

- include 'packages.yml'

# docker needs to expose its API
# so we need to push our defaults file in
- name: push docker service settings
  template:
    src: sysconfig.docker
    dest: /etc/sysconfig/docker

- name: create docker group
  group:
    name: docker

- name: add ec2 user to docker group
  # command: usermod -a -G docker ec2-user
  user:
    name: ec2-user
    groups: docker

- name: restart docker service
  service:
    name: docker
    state: restarted
