---

- name: check for supported distros
  fail: "{{ ansible_distribution }} is unsupported. Only CentOS and Ubuntu supported."
  when: ansible_distribution != 'Ubuntu' and ansible_distribution != 'CentOS'

# Install packages specific for ubuntu
- name: install prerequisite packages for Ubuntu
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
  when: ansible_distribution == "Ubuntu"
  become: true

# add Docker repo to get the latest docker
- name: add Docker repository for CentOS
  yum_repository:
    name: docker
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg
  when: ansible_distribution == "CentOS"
  become: true

# add apt key for ubuntu
- name: add Docker APT Key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  become: true

- name: add Docker repository
  apt_repository:
    filename: docker
    repo: "deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
  when: ansible_distribution == 'Ubuntu'
  become: true

# install required packages
- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - python
    - docker-engine
  become: true

# install pip
- name: get pip install script
  get_url:
    url: "https://bootstrap.pypa.io/get-pip.py"
    dest: "/tmp/get-pip.py"

- name: run pip install script
  command: python get-pip.py
  args:
    chdir: "/tmp"
    creates: /usr/bin/pip
  become: true

# install python modules needed by docker-image
- name: install docker-py
  pip:
    name: "{{item}}"
    state: present
  become: true
  with_items:
    - six
    - docker-py

# install docker-compose as it is needed by docker-image
# install 1.9.0 as per bug below:
# https://github.com/ansible/ansible/issues/20492
- name: install docker-compose
  pip:
    name: docker-compose
    state: present
    version: 1.9.0
  become: true
