---

- name: check for supported distros
  fail: "{{ ansible_distribution }} is unsupported. Only CentOS and Ubuntu supported."
  when: ansible_distribution != 'Ubuntu' and ansible_distribution != 'CentOS'

# add Docker repo to get the latest docker
- name: add Docker repository for CentOS
  yum_repository:
    name: docker
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg
  when: ansible_distribution == "CentOS"
  become: true

- block:

  - name: install prerequisite packages for Ubuntu
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - apt-transport-https
      - ca-certificates

  - name: add Docker APT Key
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add Docker Ubuntu repository
    apt_repository:
      filename: docker
      repo: "deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"

  when: ansible_distribution == "Ubuntu"
  become: true

# install required packages
- name: install packages including Docker.
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - python
    - python-pip
    - docker-ce
  become: true
  notify: restart docker

- name: install docker-py
  pip:
    name: "{{item}}"
    state: present
  become: true
  with_items:
    - six
    - docker-py

# install docker-compose as it is needed by docker-image
# install 1.9.0 as per bug below:
# https://github.com/ansible/ansible/issues/20492
- name: install docker-compose
  pip:
    name: docker-compose
    state: present
  become: true
