---
- fail: msg="undefined variable vm_groups"
  when: vm_groups is not defined

- fail: msg="variable use_azure is not defined, please set it to true."
  when: use_azure is not defined

- block:
  - name: Retrieve IP address details from Azure.
    azure_rm_publicipaddress_facts:
      name: '{{vm_pubip_name}}'
      resource_group: '{{rg_name}}'
    register: pubip_facts

  - debug: var=pubip_facts.ansible_facts.azure_publicipaddresses

  - fail: msg="One and only one IP address must be retrieved, something went wrong"
    when: pubip_facts.ansible_facts.azure_publicipaddresses|length > 1
  when: use_azure
- name: Add a Linux host to in-memory inventory.
  add_host:
    ansible_host: '{{item.properties.ipAddress}}'
    ansible_user: '{{vm_username}}'
    ansible_password: '{{vault_vm_password}}'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    hostname: '{{vm_name}}'
    groups: '{{vm_groups}}'
  with_items: '{{pubip_facts.ansible_facts.azure_publicipaddresses}}'
  when: "vm_os_type == 'Linux'"

- name: Add a Windows host to in-memory inventory.
  add_host:
    ansible_host: '{{item.properties.ipAddress}}'
    ansible_user: '{{vm_username}}'
    ansible_password: '{{vault_vm_password}}'
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 60
    ansible_winrm_read_timeout_sec: 120
    hostname: '{{vm_name}}'
    groups: '{{vm_groups}}'
  with_items: '{{pubip_facts.ansible_facts.azure_publicipaddresses}}'
  when: "vm_os_type == 'Windows'"
