---

- name: Create VNET Gateway Public IP.
  azure_rm_publicipaddress:
    resource_group: '{{azure_vnet_rg_name}}'
    name: '{{azure_vpngwip_name}}'
    allocation_method: Dynamic
    domain_name: thisisatest

- name: Include tasks to install Azure CLI.
  include_role:
    name: ansible-roles/common
    tasks_from: install-azure-cli
 
- name: Az Login.
  shell: |
    az login --service-principal -u {{lookup('env','AZURE_CLIENT_ID')}} \
    -p {{lookup('env','AZURE_SECRET')}} \
    --tenant {{lookup('env','AZURE_TENANT_ID')}}

- name: Check if VPN Gateway exists.
  shell: az network vnet-gateway show --name {{azure_vpngw_name}} -g {{azure_vnet_rg_name}}
  changed_when: false
  register: az_vpngw_exists

- name: Create VPN Gateway.
  shell: |    
    az network vnet-gateway create --name {{azure_vpngw_name}} \
    --public-ip-address {{azure_vpngwip_name}} \
    --resource-group {{azure_vnet_rg_name}} \
    --vnet {{azure_vnet_name}} \
    --gateway-type Vpn --vpn-type RouteBased --sku Basic \
    --address-prefixes {{azure_vpngw_client_address_prefixes}} \
    --location {{azure_vnet_location}}
  when: azure_vpngw_name not in az_vpngw_exists.stdout
